### PR TITLE
Update many typos and correct grammer

### PR DESCRIPTION
**Pull request by AustinLeath**
This is a simple change. I corrected the grammar and spelling of the INSTALL file.

### CODE REVIEW

**Comment by AustinLeath** [comment]
Just checking on this. Is this repository still active?

**Comment by t0k4rt** [comment]
> Just checking on this. Is this repository still active?

No ! Please do not use this library, it's old and not maintained. Please use this one "chillerlan/php-qrcode" or any other more modern.

**Comment by AustinLeath** [comment]
okay thank you! I am closing this PR

**Comment by ghost** [comment]
> > Just checking on this. Is this repository still active?
> 
> No ! Please do not use this library, it's old and not maintained. Please use this one "chillerlan/php-qrcode" or any other more modern.

@t0k4rt , Will you start maintaining again, If I create PR with supporting the new PHP version of this repository?

**Comment by AustinLeath** [comment]
> > > Just checking on this. Is this repository still active?
> > 
> > 
> > No ! Please do not use this library, it's old and not maintained. Please use this one "chillerlan/php-qrcode" or any other more modern.
> 
> @t0k4rt , Will you start maintaining again, If I create PR with supporting the new PHP version of this repository?

My guess is probably not

**Comment by t0k4rt** [comment]
@de-iyasin Sorry I won't maintain it, I have no time  to  dedicate to  this repository. As mentioned there are better alternatives out there. As an advice it's not worth it but you can still fork and update the library.

**Pull request closed without merging**
